# Generated by Django 3.2.6 on 2021-10-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=225)),
                ('PhoneNumber', models.CharField(max_length=225)),
                ('Salutation', models.CharField(choices=[('mr', 'MR'), ('mrs', 'MRS')], max_length=225)),
                ('FirstName', models.CharField(max_length=225)),
                ('MiddleName', models.CharField(max_length=225)),
                ('LastName', models.CharField(max_length=225)),
                ('Gender', models.CharField(choices=[('f', 'F'), ('m', 'M')], max_length=225)),
                ('DOB', models.CharField(max_length=225)),
                ('Address', models.CharField(max_length=225)),
                ('MaritalStatus', models.CharField(choices=[('single', 'SINGLE'), ('married', 'MARRIED')], max_length=225)),
                ('BVN', models.CharField(max_length=225)),
                ('APPID', models.CharField(blank=True, max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('DebitAccount', models.CharField(max_length=225)),
                ('Narration', models.CharField(max_length=225)),
                ('Fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ValueDate', models.CharField(max_length=225)),
                ('TransactionReference', models.CharField(max_length=225)),
                ('Currency', models.CharField(choices=[('ngn', 'NGN'), ('usd', 'USD')], max_length=225)),
            ],
        ),
    ]
